apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/rusif/catalog-service/k8s?ref=c219e7ec14d7394255a7a7ef787762fc3174217b
patchesStrategicMerge:
  - patch-env.yml
  - patch-resources.yml
  - patch-volumes.yml
configMapGenerator:
  - behavior: merge
    files:
      - application-prod.yml
    name: catalog-config
images:
  - name: catalog-service
    newName: ghcr.io/rusif/catalog-service
    newTag: c219e7ec14d7394255a7a7ef787762fc3174217b

replicas:
  - count: 2
    name: catalog-service
